import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Navigation from '../components/nav/nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const navigationItems = [
    { 
      name: 'artists', 
      href: '/artists' 
    },
    { 
      name: 'albums', 
      href: '/albums' 
    },
    { 
      name: 'songs', 
      href: '/songs' 
    }
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation links={navigationItems} />
        {children}
      </body>
    </html>
  )
}
